/* ===========================================================================
   HUNTINGTON PLACE HOA — Main site script
   ---------------------------------------------------------------------------
   All editable content (meetings, documents) lives in site-data.js.
   Do not edit this file unless you are a developer.
   =========================================================================== */

(function () {
  "use strict";

  /* ---------- Footer year ---------- */
  var yearEl = document.getElementById("year");
  if (yearEl) {
    yearEl.textContent = new Date().getFullYear();
  }

  /* ---------- Mobile nav toggle ---------- */
  var navToggle = document.getElementById("navToggle");
  var navMenu   = document.getElementById("navMenu");
  if (navToggle && navMenu) {
    navToggle.addEventListener("click", function () {
      var open = navMenu.classList.toggle("is-open");
      navToggle.setAttribute("aria-expanded", open ? "true" : "false");
    });

    navMenu.addEventListener("click", function (e) {
      if (e.target.classList.contains("nav__link")) {
        navMenu.classList.remove("is-open");
        navToggle.setAttribute("aria-expanded", "false");
      }
    });
  }

  /* ---------- Events table ---------- */
  var eventsTbody = document.getElementById("eventsTbody");
  if (eventsTbody && typeof SITE_DATA !== "undefined" && SITE_DATA.events) {
    SITE_DATA.events.forEach(function (ev) {
      var tr = document.createElement("tr");
      tr.innerHTML =
        "<td>" + ev.event    + "</td>" +
        "<td>" + ev.date     + "</td>" +
        "<td>" + ev.time     + "</td>" +
        "<td>" + ev.location + "</td>";
      eventsTbody.appendChild(tr);
    });
  }

  /* ---------- Documents: dropdown + dynamic list ---------- */
  var select  = document.getElementById("categorySelect");
  var list    = document.getElementById("documentsList");
  var library = (typeof SITE_DATA !== "undefined" && SITE_DATA.documents)
    ? SITE_DATA.documents
    : [];

  function renderDocuments(index) {
    list.innerHTML = "";
    var entry = library[index];
    if (!entry || !entry.documents.length) {
      var empty = document.createElement("li");
      empty.className   = "documents__empty";
      empty.textContent = "No documents in this category yet.";
      list.appendChild(empty);
      return;
    }

    entry.documents.forEach(function (doc) {
      var li = document.createElement("li");
      var a  = document.createElement("a");
      a.textContent = doc.title;
      a.href        = doc.url;
      a.target      = "_blank";
      a.rel         = "noopener";
      li.appendChild(a);
      list.appendChild(li);
    });
  }

  if (select && list) {
    library.forEach(function (entry, i) {
      var opt       = document.createElement("option");
      opt.value     = String(i);
      opt.textContent = entry.category;
      select.appendChild(opt);
    });

    select.addEventListener("change", function () {
      renderDocuments(parseInt(select.value, 10));
    });

    renderDocuments(0);
  }

  /* ---------- Highlight active nav section on scroll ---------- */
  var sections = document.querySelectorAll("main section[id]");
  var links    = document.querySelectorAll(".nav__link");

  function setActiveLink() {
    var pos       = window.scrollY + 90;
    var currentId = "";
    sections.forEach(function (sec) {
      if (sec.offsetTop <= pos) { currentId = sec.id; }
    });
    links.forEach(function (link) {
      link.classList.toggle("is-active", link.getAttribute("href") === "#" + currentId);
    });
  }

  window.addEventListener("scroll", setActiveLink, { passive: true });
  setActiveLink();
})();
